# Generated by Django 6.0.6 on 2026-06-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_order_payment_id_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
